"""Mapeamento cidade/aeroporto → código IATA para extração de rotas."""

CITY_TO_IATA: dict[str, str] = {
    # Brasil
    "são paulo": "GRU",
    "guarulhos": "GRU",
    "congonhas": "CGH",
    "campinas": "VCP",
    "viracopos": "VCP",
    "rio de janeiro": "GIG",
    "galeão": "GIG",
    "santos dumont": "SDU",
    "brasília": "BSB",
    "salvador": "SSA",
    "recife": "REC",
    "fortaleza": "FOR",
    "belém": "BEL",
    "manaus": "MAO",
    "curitiba": "CWB",
    "porto alegre": "POA",
    "florianópolis": "FLN",
    "belo horizonte": "CNF",
    "confins": "CNF",
    "maceió": "MCZ",
    "natal": "NAT",
    "joão pessoa": "JPA",
    "são luís": "SLZ",
    "cuiabá": "CGB",
    "campo grande": "CGR",
    "porto velho": "PVH",
    "rio branco": "RBR",
    "vitória": "VIX",
    "aracaju": "AJU",
    "teresina": "THE",
    "macapá": "MCP",
    "palmas": "PMW",
    # Internacional — Américas
    "miami": "MIA",
    "nova york": "JFK",
    "new york": "JFK",
    "los angeles": "LAX",
    "toronto": "YYZ",
    "montreal": "YUL",
    "buenos aires": "EZE",
    "santiago": "SCL",
    "lima": "LIM",
    "bogotá": "BOG",
    "bogota": "BOG",
    "cidade do panamá": "PTY",
    "cancún": "CUN",
    "cancun": "CUN",
    "orlando": "MCO",
    "washington": "IAD",
    "chicago": "ORD",
    "dallas": "DFW",
    "são francisco": "SFO",
    "san francisco": "SFO",
    # Internacional — Europa
    "lisboa": "LIS",
    "madrid": "MAD",
    "paris": "CDG",
    "londres": "LHR",
    "frankfurt": "FRA",
    "amsterdam": "AMS",
    "roma": "FCO",
    "barcelona": "BCN",
    "milão": "MXP",
    "munique": "MUC",
    "zurique": "ZRH",
    "viena": "VIE",
    "copenhague": "CPH",
    "estocolmo": "ARN",
    # Internacional — outros
    "dubai": "DXB",
    "doha": "DOH",
    "tóquio": "NRT",
    "toquio": "NRT",
    "cidade do cabo": "CPT",
    "joanesburgo": "JNB",
    "sydney": "SYD",
    "bangkok": "BKK",
    "cingapura": "SIN",
    "hong kong": "HKG",
}

# Lista curada para autocomplete do frontend.
AIRPORTS_LIST: list[dict[str, str]] = [
    {"iata": "GRU", "label": "GRU — São Paulo / Guarulhos"},
    {"iata": "CGH", "label": "CGH — São Paulo / Congonhas"},
    {"iata": "VCP", "label": "VCP — Campinas / Viracopos"},
    {"iata": "GIG", "label": "GIG — Rio de Janeiro / Galeão"},
    {"iata": "SDU", "label": "SDU — Rio de Janeiro / Santos Dumont"},
    {"iata": "BSB", "label": "BSB — Brasília"},
    {"iata": "SSA", "label": "SSA — Salvador"},
    {"iata": "REC", "label": "REC — Recife"},
    {"iata": "FOR", "label": "FOR — Fortaleza"},
    {"iata": "BEL", "label": "BEL — Belém"},
    {"iata": "MAO", "label": "MAO — Manaus"},
    {"iata": "CWB", "label": "CWB — Curitiba"},
    {"iata": "POA", "label": "POA — Porto Alegre"},
    {"iata": "FLN", "label": "FLN — Florianópolis"},
    {"iata": "CNF", "label": "CNF — Belo Horizonte / Confins"},
    {"iata": "MCZ", "label": "MCZ — Maceió"},
    {"iata": "NAT", "label": "NAT — Natal"},
    {"iata": "JPA", "label": "JPA — João Pessoa"},
    {"iata": "SLZ", "label": "SLZ — São Luís"},
    {"iata": "CGB", "label": "CGB — Cuiabá"},
    {"iata": "CGR", "label": "CGR — Campo Grande"},
    {"iata": "VIX", "label": "VIX — Vitória"},
    {"iata": "AJU", "label": "AJU — Aracaju"},
    {"iata": "MIA", "label": "MIA — Miami"},
    {"iata": "JFK", "label": "JFK — Nova York"},
    {"iata": "LAX", "label": "LAX — Los Angeles"},
    {"iata": "MCO", "label": "MCO — Orlando"},
    {"iata": "IAD", "label": "IAD — Washington / Dulles"},
    {"iata": "ORD", "label": "ORD — Chicago"},
    {"iata": "DFW", "label": "DFW — Dallas"},
    {"iata": "SFO", "label": "SFO — São Francisco"},
    {"iata": "YYZ", "label": "YYZ — Toronto"},
    {"iata": "YUL", "label": "YUL — Montreal"},
    {"iata": "EZE", "label": "EZE — Buenos Aires"},
    {"iata": "SCL", "label": "SCL — Santiago"},
    {"iata": "LIM", "label": "LIM — Lima"},
    {"iata": "BOG", "label": "BOG — Bogotá"},
    {"iata": "PTY", "label": "PTY — Cidade do Panamá"},
    {"iata": "CUN", "label": "CUN — Cancún"},
    {"iata": "LIS", "label": "LIS — Lisboa"},
    {"iata": "MAD", "label": "MAD — Madrid"},
    {"iata": "CDG", "label": "CDG — Paris"},
    {"iata": "LHR", "label": "LHR — Londres"},
    {"iata": "FRA", "label": "FRA — Frankfurt"},
    {"iata": "AMS", "label": "AMS — Amsterdam"},
    {"iata": "FCO", "label": "FCO — Roma"},
    {"iata": "BCN", "label": "BCN — Barcelona"},
    {"iata": "MXP", "label": "MXP — Milão"},
    {"iata": "MUC", "label": "MUC — Munique"},
    {"iata": "ZRH", "label": "ZRH — Zurique"},
    {"iata": "VIE", "label": "VIE — Viena"},
    {"iata": "DXB", "label": "DXB — Dubai"},
    {"iata": "DOH", "label": "DOH — Doha"},
    {"iata": "NRT", "label": "NRT — Tóquio"},
    {"iata": "CPT", "label": "CPT — Cidade do Cabo"},
    {"iata": "JNB", "label": "JNB — Joanesburgo"},
    {"iata": "SYD", "label": "SYD — Sydney"},
    {"iata": "BKK", "label": "BKK — Bangkok"},
    {"iata": "SIN", "label": "SIN — Cingapura"},
    {"iata": "HKG", "label": "HKG — Hong Kong"},
]
